name: Build and deploy personal website

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: 'us-west-2'
  AWS_BUCKET_NAME: 's3://joshualester-dot-com'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::528757819881:role/GitHubAction-Deployer
          role-session-name: GitHubAction-Deployer
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: npm i
        working-directory: web

      - name: Build
        run: npm run build
        working-directory: web

      - name: Generate
        run: npm run generate
        working-directory: web

      - name: Transfer files to S3 Bucket
        run: aws s3 sync dist/ ${{env.AWS_BUCKET_NAME}} --delete
        working-directory: web
